---
  - name: Init Swarm Master
    hosts: masters
    gather_facts: False
    remote_user: core
    tasks:
      - name: Swarm Init
        command: docker swarm init --advertise-addr {{ inventory_hostname }}

      - name: Get Worker Token
        command: docker swarm join-token worker
        register: worker_token

      - name: Show Worker Token
        debug: var=worker_token.stdout

      - name: Master Token
        command: docker swarm join-token manager
        register: master_token

      - name: Show Master Token
        debug: var=master_token.stdout
